spring.application.name=reserva
server.port=8080
# Datasource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username="SG"
spring.datasource.password="SAN_GABRIEL_BIBLIOTECA"
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

biblioteca.ejemplar.url=http://localhost:8081
biblioteca.persona.url=http://localhost:8082
