spring.application.name=reserva
server.port=8087
# Datasource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username="SG"
spring.datasource.password="SAN_GABRIEL_BIBLIOTECA"
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


logging.level.root=INFO

logging.level.com.biblioteca=DEBUG

#formato del log, incluyendo timestamp, nivel de log, clase y mensaje
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

#Nombre del archivo de log
logging.file.name=persona.log

#Nivel de log para el archivo, en este caso se registra todo desde DEBUG en adelante
logging.level.file=INFO

#Nivel de log para el paquete de la aplicacion en el archivo, se puede configurar diferente al nivel de consola
logging.level.com.biblioteca.file=DEBUG

#Formato del log para el archivo, similar al de la consola pero con un formato diferente si se desea
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
